name: ci-recommender-job

on:
  push:
    branches: [main]
    paths:
      - apps/recommender-job/**
      - .github/workflows/ci-recommender-job.yaml
      - .github/workflows/build-push.yaml

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-push.yaml
    with:
      service: recommender-job
    secrets: inherit
